Repository matdaaiga-kr/matdaaiga-kr.github.io, pull requests merged in 2025-03, with the labels that each got.

#41 fix: change icon-globe.svg
  assets/icon-globe.svg
  src/MatdaAIga.Generator/input/android-icon-144x144.png
  src/MatdaAIga.Generator/input/android-icon-192x192.png
  src/MatdaAIga.Generator/input/android-icon-36x36.png
  src/MatdaAIga.Generator/input/android-icon-48x48.png
  src/MatdaAIga.Generator/input/android-icon-72x72.png
  src/MatdaAIga.Generator/input/android-icon-96x96.png
  src/MatdaAIga.Generator/input/apple-icon-114x114.png
  src/MatdaAIga.Generator/input/apple-icon-120x120.png
  src/MatdaAIga.Generator/input/apple-icon-144x144.png
  src/MatdaAIga.Generator/input/apple-icon-152x152.png
  src/MatdaAIga.Generator/input/apple-icon-180x180.png
  src/MatdaAIga.Generator/input/apple-icon-57x57.png
  src/MatdaAIga.Generator/input/apple-icon-60x60.png
  src/MatdaAIga.Generator/input/apple-icon-72x72.png
  src/MatdaAIga.Generator/input/apple-icon-76x76.png
  src/MatdaAIga.Generator/input/apple-icon-precomposed.png
  src/MatdaAIga.Generator/input/apple-icon.png
  src/MatdaAIga.Generator/input/favicon-16x16.png
  src/MatdaAIga.Generator/input/favicon-32x32.png
  src/MatdaAIga.Generator/input/favicon-96x96.png
  src/MatdaAIga.Generator/input/favicon.ico
  src/MatdaAIga.Generator/input/ms-icon-144x144.png
  src/MatdaAIga.Generator/input/ms-icon-150x150.png
  src/MatdaAIga.Generator/input/ms-icon-310x310.png
  src/MatdaAIga.Generator/input/ms-icon-70x70.png
Labels: enhancement

#42 Feature/21 service layer interface
  src/MatdaAIga.LinkConverter/Controllers/IConverterController.cs
  src/MatdaAIga.LinkConverter/Models/LinkModel.cs
  src/MatdaAIga.LinkConverter/Services/IConverterService.cs
Labels: task

#39 [task/18-link-page-css] 링크 페이지 전용 CSS 생성
  src/MatdaAIga.Generator/input/_layout.cshtml
  src/MatdaAIga.Generator/input/scss/_overrides.scss
Labels: task

#43 [Task/23] 마크다운 링크 페이지 삽입 서비스 레이어 : SaveAsync() 구현
  Directory.Build.props
  src/MatdaAIga.LinkConverter/Services/ConverterService.cs
  src/MatdaAIga.LinkConverter/Services/IConverterService.cs
  tests/MatdaAIga.LinkConverter.Tests/ConverterServiceTest.cs
  tests/MatdaAIga.LinkConverter.Tests/MatdaAIga.LinkConverter.Tests.csproj
  tests/MatdaAIga.LinkConverter.Tests/files/placeholder-0.md
  tests/MatdaAIga.LinkConverter.Tests/files/placeholder-1.md
  tests/MatdaAIga.LinkConverter.Tests/files/placeholder-2.md
  tests/MatdaAIga.LinkConverter.Tests/files/placeholder-3-text.md
  tests/MatdaAIga.LinkConverter.Tests/files/placeholder-3.md
Labels: enhancement, task

#48 ConverterController.RunAsync() 구현
  Directory.Build.props
  src/MatdaAIga.LinkConverter/Controllers/ConverterController.cs
  src/MatdaAIga.LinkConverter/Options/ArgumentOptions.cs
  tests/MatdaAIga.LinkConverter.Tests/ArgumentOptionsTests.cs
  tests/MatdaAIga.LinkConverter.Tests/MatdaAIga.LinkConverter.Tests.csproj
  tests/MatdaAIga.LinkConverter.Tests/RunAsyncTests.cs
  tests/MatdaAIga.LinkConverter.Tests/UnitTest1.cs
Labels: task
