Repository matdaaiga-kr/matdaaiga-kr.github.io, pull requests merged in 2025-02, with the labels that each got.

#28 Add console app for link converter
  .github/workflows/publish-gh-pages.yaml
  Directory.Build.props
  MatdaAIga.sln
  src/MatdaAIga.Generator/MatdaAIga.Generator.csproj
  src/MatdaAIga.LinkConverter/MatdaAIga.LinkConverter.csproj
  src/MatdaAIga.LinkConverter/Program.cs
  src/MatdaAIga.LinkConverter/appsettings.json
  tests/MatdaAIga.LinkConverter.Tests/MatdaAIga.LinkConverter.Tests.csproj
  tests/MatdaAIga.LinkConverter.Tests/UnitTest1.cs
Labels: enhancement, task

#31 Add AfterBuild trigger event
  .github/workflows/publish-gh-pages.yaml
  src/MatdaAIga.Generator/MatdaAIga.Generator.csproj
Labels: bug

#26 yaml schema configuration
  src/MatdaAIga.Generator/input/pages/links.yaml
  src/MatdaAIga.Generator/input/schema/links.yaml.json
Labels: enhancement, task

#27 Change favicons
  assets/icon-150x150.svg
  assets/icon-globe.svg
  assets/icon-typo-beta.svg
  assets/icon-typo.svg
  src/MatdaAIga.Generator/input/android-icon-144x144.png
  src/MatdaAIga.Generator/input/android-icon-192x192.png
  src/MatdaAIga.Generator/input/android-icon-36x36.png
  src/MatdaAIga.Generator/input/android-icon-48x48.png
  src/MatdaAIga.Generator/input/android-icon-72x72.png
  src/MatdaAIga.Generator/input/android-icon-96x96.png
  src/MatdaAIga.Generator/input/apple-icon-114x114.png
  src/MatdaAIga.Generator/input/apple-icon-120x120.png
  src/MatdaAIga.Generator/input/apple-icon-144x144.png
  src/MatdaAIga.Generator/input/apple-icon-152x152.png
  src/MatdaAIga.Generator/input/apple-icon-180x180.png
  src/MatdaAIga.Generator/input/apple-icon-57x57.png
  src/MatdaAIga.Generator/input/apple-icon-60x60.png
  src/MatdaAIga.Generator/input/apple-icon-72x72.png
  src/MatdaAIga.Generator/input/apple-icon-76x76.png
  src/MatdaAIga.Generator/input/apple-icon-precomposed.png
  src/MatdaAIga.Generator/input/apple-icon.png
  src/MatdaAIga.Generator/input/favicon-16x16.png
  src/MatdaAIga.Generator/input/favicon-32x32.png
  src/MatdaAIga.Generator/input/favicon-96x96.png
  src/MatdaAIga.Generator/input/favicon.ico
  src/MatdaAIga.Generator/input/ms-icon-144x144.png
  src/MatdaAIga.Generator/input/ms-icon-150x150.png
  src/MatdaAIga.Generator/input/ms-icon-310x310.png
  src/MatdaAIga.Generator/input/ms-icon-70x70.png
Labels: enhancement

#29 Add : March Global AI Daegu Event Page
  src/MatdaAIga.Generator/input/images/posts/2025/02/global-ai-bootcamp-daegu-2025-00.png
  src/MatdaAIga.Generator/input/images/posts/2025/02/global-ai-bootcamp-daegu-2025-01.jpg
  src/MatdaAIga.Generator/input/posts/2025/global-ai-bootcamp-daegu-2025.md
Labels: blog

#35 상단 네비바에서 "posts" 링크 빼기
  src/MatdaAIga.Generator/input/_navbar.cshtml
  src/MatdaAIga.Generator/input/links/links.yaml
  src/MatdaAIga.Generator/input/pages/_directory.yml
Labels: bug, enhancement

#37 태그 가나다순 정렬
  src/MatdaAIga.Generator/input/index.cshtml
Labels: bug, enhancement

#32 [task/17-links.md] 링크 페이지 마크다운 생성
  src/MatdaAIga.Generator/input/pages/_directory.yml
  src/MatdaAIga.Generator/input/pages/links.md
Labels: task

#40 Links 페이지에 아이콘 링크 추가
  src/MatdaAIga.Generator/input/icons/eventus.png
  src/MatdaAIga.Generator/input/icons/globalai.svg
  src/MatdaAIga.Generator/input/icons/linkedin.svg
  src/MatdaAIga.Generator/input/icons/matdaaiga.svg
  src/MatdaAIga.Generator/input/pages/links.md
  src/MatdaAIga.Generator/settings.yml
Labels: enhancement
